// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: service_logic.proto

package hwgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//请求参数
type CommonInputRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputJsonString string `protobuf:"bytes,1,opt,name=InputJsonString,proto3" json:"InputJsonString,omitempty"`
}

func (x *CommonInputRequest) Reset() {
	*x = CommonInputRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_logic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonInputRequest) ProtoMessage() {}

func (x *CommonInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_logic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonInputRequest.ProtoReflect.Descriptor instead.
func (*CommonInputRequest) Descriptor() ([]byte, []int) {
	return file_service_logic_proto_rawDescGZIP(), []int{0}
}

func (x *CommonInputRequest) GetInputJsonString() string {
	if x != nil {
		return x.InputJsonString
	}
	return ""
}

//输出信息
type CommonOutputResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutputJsonString string `protobuf:"bytes,1,opt,name=OutputJsonString,proto3" json:"OutputJsonString,omitempty"`
}

func (x *CommonOutputResponse) Reset() {
	*x = CommonOutputResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_logic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonOutputResponse) ProtoMessage() {}

func (x *CommonOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_logic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonOutputResponse.ProtoReflect.Descriptor instead.
func (*CommonOutputResponse) Descriptor() ([]byte, []int) {
	return file_service_logic_proto_rawDescGZIP(), []int{1}
}

func (x *CommonOutputResponse) GetOutputJsonString() string {
	if x != nil {
		return x.OutputJsonString
	}
	return ""
}

var File_service_logic_proto protoreflect.FileDescriptor

var file_service_logic_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x22, 0x3e, 0x0a, 0x12,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x42, 0x0a, 0x14,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4a, 0x73,
	0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x32, 0x5b, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4a, 0x0a, 0x10, 0x43, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x19, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x2f, 0x3b, 0x68, 0x77, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_service_logic_proto_rawDescOnce sync.Once
	file_service_logic_proto_rawDescData = file_service_logic_proto_rawDesc
)

func file_service_logic_proto_rawDescGZIP() []byte {
	file_service_logic_proto_rawDescOnce.Do(func() {
		file_service_logic_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_logic_proto_rawDescData)
	})
	return file_service_logic_proto_rawDescData
}

var file_service_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_logic_proto_goTypes = []interface{}{
	(*CommonInputRequest)(nil),   // 0: logic.CommonInputRequest
	(*CommonOutputResponse)(nil), // 1: logic.CommonOutputResponse
}
var file_service_logic_proto_depIdxs = []int32{
	0, // 0: logic.CommonService.CallCommonMethod:input_type -> logic.CommonInputRequest
	1, // 1: logic.CommonService.CallCommonMethod:output_type -> logic.CommonOutputResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_logic_proto_init() }
func file_service_logic_proto_init() {
	if File_service_logic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_logic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonInputRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_logic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonOutputResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_logic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_logic_proto_goTypes,
		DependencyIndexes: file_service_logic_proto_depIdxs,
		MessageInfos:      file_service_logic_proto_msgTypes,
	}.Build()
	File_service_logic_proto = out.File
	file_service_logic_proto_rawDesc = nil
	file_service_logic_proto_goTypes = nil
	file_service_logic_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommonServiceClient is the client API for CommonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommonServiceClient interface {
	CallCommonMethod(ctx context.Context, in *CommonInputRequest, opts ...grpc.CallOption) (*CommonOutputResponse, error)
}

type commonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommonServiceClient(cc grpc.ClientConnInterface) CommonServiceClient {
	return &commonServiceClient{cc}
}

func (c *commonServiceClient) CallCommonMethod(ctx context.Context, in *CommonInputRequest, opts ...grpc.CallOption) (*CommonOutputResponse, error) {
	out := new(CommonOutputResponse)
	err := c.cc.Invoke(ctx, "/logic.CommonService/CallCommonMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonServiceServer is the server API for CommonService service.
type CommonServiceServer interface {
	CallCommonMethod(context.Context, *CommonInputRequest) (*CommonOutputResponse, error)
}

// UnimplementedCommonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommonServiceServer struct {
}

func (*UnimplementedCommonServiceServer) CallCommonMethod(context.Context, *CommonInputRequest) (*CommonOutputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallCommonMethod not implemented")
}

func RegisterCommonServiceServer(s *grpc.Server, srv CommonServiceServer) {
	s.RegisterService(&_CommonService_serviceDesc, srv)
}

func _CommonService_CallCommonMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).CallCommonMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logic.CommonService/CallCommonMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).CallCommonMethod(ctx, req.(*CommonInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logic.CommonService",
	HandlerType: (*CommonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallCommonMethod",
			Handler:    _CommonService_CallCommonMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_logic.proto",
}
